### ISSUE TITLE
Разработать макет главной страницы для заказчика

### ISSUE THREAD

**Issue by kuvatov** [AttractorSchool/ESDP-AP-10-3#10]
## Что необходимо сделать
Необходимо нарисовать макет главной страницы веб-приложения

## Для чего это нужно
Для демонстрации проекта заказчику, чтобы команда получила подтверждение или корректировки в своем видении проекта

## Что нужно показать
Макет должен содержать несколько блоков:

- меню навигации (логотип, форма поиска с кнопкой, а также кнопка входа/выхода)
- контентная часть (таблица с информацией о тендерах)
- footer с информацией о заказчике (наименование компании)

## Планируемое время
4 часа

**Comment by bitterslim** [comment]
Сделано
https://docs.google.com/presentation/d/1tUz1PrD6cm9byL6EdWgXujO8k6KNbP9KyYIRwy8wrIg/edit?usp=sharing

**Comment by kuvatov** [comment]
Затрачено 4 часа
