### ISSUE TITLE
Исправить извлечение предельных цен товаров из PDF-файла[4]

### ISSUE THREAD

**Issue by YerbolZhulniyazov** [AttractorSchool/ESDP-AP-10-3#105]
## Что нужно сделать 
Исправить загрузку предельных цен из PDF-файла

## Для чего это нужно 
Была ошибка в первоначальной версии. При выгрузке данных из PDF-файла в нашу базу данных создавались лишние записи

## Планируемое время

4 часов

**Comment by gituser2s** [comment]
Задача была выполнена вместе с задачей https://github.com/AttractorSchool/ESDP-AP-10-3/issues/96
