### ISSUE TITLE
Добавить базовый шаблон в проект

### ISSUE THREAD

**Issue by kuvatov** [AttractorSchool/ESDP-AP-10-3#11]
## Что нужно сделать
Необходимо в приложении **smarttender** сделать следующее:

- [ ] создать папку **templates** для хранения всех шаблонов (_.html_)
- [ ] добавить базовый шаблон - _base.html_

## Для чего это нужно

- папка **templates** нужна для хранения всех шаблонов приложения
- базовый шаблон нужен для того, чтобы содержать в себе одинаковые элементы для всех страниц

## Что нужно отразить в базовом шаблоне

- [ ] меню навигации (логотип, форма поиска с кнопкой, а также кнопка входа/выхода)
- [ ] footer с информацией о заказчике (наименование компании)

## Планируемое время
5 часов

**Comment by Novel1** [comment]
Сделано
