### ISSUE TITLE
Работа с Excel файлами 

### ISSUE THREAD

**Issue by Novel1** [AttractorSchool/ESDP-AP-10-3#15]
Для чего это нужно и мотивация:
---
   
Уметь работать с Excel файлами.
В дальнейшим если столкнетесь с работай с Excel, знание библиотеки **openpyxl** будет кстати, она предоставляет возможность автоматизировать создание, редактирование и анализ электронных таблиц Excel.

Что нужно сделать:
---
Установить и разобраться с библиотекой  **openpyxl**

Решение
---
Установка: pip install openpyxl
Инструкция: https://www.youtube.com/watch?v=d5jHpPSp5uI&t=420s
Документация: https://pypi.org/project/openpyxl/

Планируемое время работы
---
4 часа

**Comment by kuvatov** [comment]
Библиотека openpyxl добавлена в проект и используется в функции парсинга Excel таблиц
