### ISSUE TITLE
Добавить html страницы в приложение smarttender с выводом таблицы из БД

### ISSUE THREAD

**Issue by gituser2s** [AttractorSchool/ESDP-AP-10-3#17]
## Что нужно сделать:

- [ ] Добавить главную страницу с выводом таблицы из БД

Необходимо реализовать frontend-часть приложения smarttender, в частности главную страницу:

- Index страница - index.html

## Что нужно отобразить на страницах:
На index странице будут отображаться данные с таблицы Excel.
Заполнять страницы необходимо с использованием базового шаблона, который находиться в base.html в папке templates
Примерный внешний вид сайта есть в данном макете: https://docs.google.com/presentation/d/1tUz1PrD6cm9byL6EdWgXujO8k6KNbP9KyYIRwy8wrIg/edit#slide=id.g241ed10ebde_1_15

## Планируемое время

5 часов

**Comment by kuvatov** [comment]
Затратил 5 часов
