### ISSUE TITLE
Создать макет-шаблон базы данных 

### ISSUE THREAD

**Issue by gituser2s** [AttractorSchool/ESDP-AP-10-3#18]
## Что нужно сделать

Необходимо в графическом редакторе или другом инструменте начертить макет базы данных, который будет описывать все необходимые модели для работы приложения 

## Для чего это нужно

Данный шаблон необходимо будет продемонстрировать ментору, чтобы удостовериться в работоспособности и актуальности моделей

## Планируемое время 

3 часа

**Comment by kuvatov** [comment]
![Tender](https://github.com/AttractorSchool/ESDP-AP-10-3/assets/88473072/43dd3409-a632-4a29-be3a-076fa9055351)
Затрачено 3 часа
