### ISSUE TITLE
Изучить принципы работы с программами Docker и Swagger

### ISSUE THREAD

**Issue by YerbolZhulniyazov** [AttractorSchool/ESDP-AP-10-3#2]
## Конечный результат:
Иметь представление как работают программы **Docker** и **Swagger**

## План решения:
Каждый член команды найдет в интернете документацию, примеры и изучит их.

## Мотивация:
Во время работы над проектом **Docker** позволет доставлять приложения на машины (локальный компьютер или удаленные сервера) и запускать их в изолированном окружении. Так же позволет запускать на одном хосте множество приложении одновременно.
**Swagger** на основе кода или набора правил автоматически сгенерирует документацию в формате JSON-файла. Ее можно будет встроить на страницу сайта или в приложение, чтобы пользователи могли интерактивно знакомиться с документацией.
Таким образом вышеуказанные программы облегчат работу над проектом

## Планируемое время
3 часа

**Comment by Novel1** [comment]
Выполнено

**Comment by gituser2s** [comment]
Выполнено

**Comment by kuvatov** [comment]
выполнено
