### ISSUE TITLE
Изучить способы извлечения наборы данных электронной таблицы Google

### ISSUE THREAD

**Issue by Novel1** [AttractorSchool/ESDP-AP-10-3#20]
**Что нужно сделать:** 
Изучить способы извлечения наборы данных электронной таблицы Google и определить их применимость в нашем проекте. Узнать как можно эффективно применить электронную таблицу Google  для добавления новой функциональности в наш проект.

---
__Мотивация:__
Если не будет альтернативных решений, электронной таблицы Google станет важным инструментом для дальнейшей разработки проекта, как необходимая функциональность.

---
**Планируемое время работы:**
3 часа

**Comment by bitterslim** [comment]
Документация создана и добавлена в wiki проекта:
https://github.com/AttractorSchool/ESDP-AP-10-3/wiki/%D0%98%D0%B7%D0%B2%D0%BB%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B7-%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B-Google-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-Python
