### ISSUE TITLE
Создание таблицы для заказчика 

### ISSUE THREAD

**Issue by Novel1** [AttractorSchool/ESDP-AP-10-3#21]
**Что нужно сделать:**
На встречи с заказчиком была нарисована таблица, в виде макета для интерфейса страницы. 
Заказчик попросил реализовать ее в электронном виде. 

---
**Фото таблицы:**
![Screenshot_1](https://github.com/AttractorSchool/ESDP-AP-10-3/assets/75561660/6b8725b4-a278-4147-883d-f0be3a70d9af)

---
**Мотивация:**
Макет в таком виде поможет нам лучше разобраться с таблицей, и мы сможем точно определить, соответствует ли текущий макет требованиям заказчика для нашего приложения.

---
**Планируемое время:**
2,5 часа

**Comment by YerbolZhulniyazov** [comment]
Затраченное время - 2,5 часа
ссылка для команды: https://docs.google.com/document/d/1-iK_mC9LiPJbfWl8q4PoykA2b_ValyGGB6ojL_htxEU/edit?usp=share_link
Для отправки Заказчику файл будет отправлен в Телеграмм чат команды
