### ISSUE TITLE
Добавить функционал аутентификации пользователя

### ISSUE THREAD

**Issue by Novel1** [AttractorSchool/ESDP-AP-10-3#24]
**Что нужно сделать:**
---
-  Создать папку accounts.
- Добавить необходимые файлы, для разработки аутентификации.
- Добавить HTML шаблоны. 

**Для чего это нужно:**
---
В основном для ограничения доступа к функционалу пользователя. Аутентификация позволяет ограничить доступ к определенным разделам или функциям веб-приложения.

**Как это сделать:**
---

1. Создание папки "accounts":
Папка будет содержать файлы связанные с аутентификации пользователя.
2. В папке "accounts" необходимо создать следующие файлы:
Файл urls: В файле определяют url-маршруты связанные с аутентификации пользователя

**Планируемое время:**
---
5 часов

**Comment by bitterslim** [comment]
Сделано
