### ISSUE TITLE
Подготовить вопросы ко встрече с заказчиком

### ISSUE THREAD

**Issue by YerbolZhulniyazov** [AttractorSchool/ESDP-AP-10-3#3]
## Конечный результат:
Собраны вопросы от всех членов команды и внесены в единый список вопросов

## План решения:
Каждый член команды повторно проходится по тех заданию и составляет вопросы.
Проведение встречи в 19:00 и составление общего списка вопросов к Заказчику. 
Ссылка на ТЗ - https://almaty-crm.attractor-school.com/esdp/team-document/22

## Мотивация:
Список вопросов необходим для уточнения  концепции проекта и прояснения деталей по реализации.

## Критерии приемки:
Получены ответы на вопросы от Заказчика.

## Планируемое время
1,5 часа

**Comment by kuvatov** [comment]
- [ ] Как устроен текущий процесс
- [ ] Что означают наименования столбцов
- [ ] Какой бот, для чего
- [ ] Имеется ли своя база
- [ ] Какие сайты мед. учреждений для выгрузки тендеров
- [ ] Какую информацию нужно хранить
- [ ] Как должна выглядеть программа
- [ ] Какие пользователи будут иметь доступ
- [ ] Логин/пароль от сайта https://ph.center/Order
- [ ] Подробнее о 4 пункте
- [ ] Возможность позвонить через телефонию
- [ ] Что за внешние ссылки (пункт 6)
- [ ] С какими еще интернет ресурсами программа должна сравнивать цены

**Comment by kuvatov** [comment]
Провели первую встречу с заказчиком и получили ответы на интересующие нас вопросы.
Договорились о встрече в офисе заказчика для ознакомления с процессом текущей работы. Предварительно договорились на среду (10.05.2023). Будет создана отдельная задача по встрече с заказчиком.
