### ISSUE TITLE
Изменить модель "Tender". Добавить возможность редактирования. [5]

### ISSUE THREAD

**Issue by bitterslim** [AttractorSchool/ESDP-AP-10-3#38]
## Что нужно сделать
Добавить новые поля в модель _Tender_. Добавить возможность редактирования. Подключить JS скрипты для избежание обновления страницы при редактирование.

## Для чего это нужно
По требованию заказчика, приложение должно иметь функцию редактирования значений модели _Tender_. Так же для  упрощения работы со стороны заказчика, при редактировании страница не обновляется

## Как это сделать
1. Добавить поля в модель _Tender_
2. Добавить метод редактирования тендерных данных
3. Подключить JS скрипты
4. Изменить индексную страницу

## Планируемое время
5 часов

**Comment by YerbolZhulniyazov** [comment]
Фактическое время выполнения задачи - 6 часов
