### ISSUE TITLE
Доработать выбор товаров [4]

### ISSUE THREAD

**Issue by Novel1** [AttractorSchool/ESDP-AP-10-3#72]
## Описание проблемы
В модальном окне была кнопка подбора товара, и после изменения модели, подбор товара стал работать неправильно.
Необходимо восстановить подбор товаров в модальном окне.

## Что нужно сделать

1. Изучить код модального окна и представления, связанные с выборкой товаров, чтобы понять, в чем заключаются проблемы.
2. Исправить код, который привел к неработоспособности выборки товаров в модальном окне.
3. Зафиксировать изменения.

## Примечания
Возможно придется полностью переделать представление и JavaScript код.

## Планируемое время
3 часа

**Comment by YerbolZhulniyazov** [comment]
Фактическое время выполнения-4 часа
