### ISSUE TITLE
Разработать функционал парсинга технической спецификации объявления [5]

### ISSUE THREAD

**Issue by kuvatov** [AttractorSchool/ESDP-AP-10-3#98]
## Что нужно сделать
Разработать функционал парсинга технической спецификации объявления и сохранения в БД

## Для чего это нужно
Для хранения и вывода дополнительной информации об объявлении

## Планируемое время
5 часов

**Comment by YerbolZhulniyazov** [comment]
Решили сохранять только ссылку
